name: vantage-ai
services:
  # Backend API Service
  - name: api
    source_dir: /
    dockerfile_path: infra/Dockerfile.api
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: META_APP_ID
        scope: RUN_TIME
        type: SECRET
      - key: META_APP_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: LINKEDIN_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: LINKEDIN_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: BRAVE_SEARCH_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"

  # Frontend Service
  - name: web
    source_dir: /web
    dockerfile_path: infra/Dockerfile.web
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${api.PUBLIC_URL}/api
      - key: NODE_ENV
        value: production

  # Worker Service
  - name: worker
    source_dir: /
    dockerfile_path: infra/Dockerfile.worker
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: META_APP_ID
        scope: RUN_TIME
        type: SECRET
      - key: META_APP_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: LINKEDIN_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: LINKEDIN_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: BRAVE_SEARCH_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"

databases:
  - name: vantage-ai-db
    engine: PG
    version: "14"
    size: db-s-1vcpu-1gb
    num_nodes: 1

# Health checks
health_check:
  http_path: /healthz
  initial_delay_seconds: 10
  period_seconds: 10
  timeout_seconds: 5
  success_threshold: 1
  failure_threshold: 3
