groups:
- name: vantage-database
  rules:
  - alert: DatabaseDown
    expr: up{job="postgres"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "PostgreSQL database is down"
      description: "Database health check has been failing for more than 1 minute"

  - alert: DatabaseHighConnections
    expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High database connection usage"
      description: "Database connections are above 80% of maximum"

  - alert: DatabaseSlowQueries
    expr: rate(pg_stat_database_tup_returned[5m]) / rate(pg_stat_database_tup_fetched[5m]) < 0.1
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Slow database queries detected"
      description: "Database query efficiency is below 10%"

  - alert: DatabaseDiskSpace
    expr: (pg_database_size_bytes / 1024 / 1024 / 1024) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Database disk space warning"
      description: "Database size is above 80GB"
