name: E2E Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vantage_ai
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install Python dependencies
      run: |
        cd /Users/saban/Desktop/NVC LAB/VANTAGE AI
        pip install -r requirements.txt

    - name: Install web dependencies
      run: |
        cd web
        npm ci

    - name: Install Playwright browsers
      run: |
        cd web
        npx playwright install --with-deps

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=postgresql+psycopg://postgres:postgres@localhost:5432/vantage_ai" >> .env
        echo "REDIS_URL=redis://localhost:6379" >> .env
        echo "E2E_MOCKS=true" >> .env
        echo "ENVIRONMENT=testing" >> .env
        echo "SECRET_KEY=test-secret-key-for-e2e-testing-only" >> .env
        echo "CLERK_JWKS_URL=https://test-clerk.clerk.accounts.dev/.well-known/jwks.json" >> .env
        echo "CLERK_ISSUER=https://test-clerk.clerk.accounts.dev" >> .env

    - name: Run database migrations
      run: |
        cd /Users/saban/Desktop/NVC LAB/VANTAGE AI
        alembic upgrade head

    - name: Seed test data
      run: |
        cd /Users/saban/Desktop/NVC LAB/VANTAGE AI
        chmod +x scripts/seed_demo.sh
        ./scripts/seed_demo.sh --env testing

    - name: Start API server
      run: |
        cd /Users/saban/Desktop/NVC LAB/VANTAGE AI
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 10
      env:
        DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/vantage_ai
        REDIS_URL: redis://localhost:6379
        E2E_MOCKS: true
        ENVIRONMENT: testing

    - name: Start web server
      run: |
        cd web
        npm run build
        npm start &
        sleep 15
      env:
        BASE_URL: http://localhost:3000
        API_BASE: http://localhost:8000/api/v1
        E2E_MOCKS: true

    - name: Wait for services to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:8000/api/v1/health; do sleep 2; done'
        timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'

    - name: Run E2E tests
      run: |
        cd web
        npm run test:e2e
      env:
        BASE_URL: http://localhost:3000
        E2E_MOCKS: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: web/playwright-report/
        retention-days: 30

    - name: Upload test traces
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-traces
        path: web/test-results/
        retention-days: 30

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-screenshots
        path: web/test-results/
        retention-days: 30

    - name: Comment PR with test results
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ E2E tests failed. Check the [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details and download artifacts for traces and screenshots.'
          })
